

-----------------------------------ONLINE_CUSTOMER---------------------------

CREATE TABLE ONLINE_CUSTOMER
(
    CID INT,
    NAME VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO ONLINE_CUSTOMER VALUES
(101,'RAHUL','RAJKOT'),
(103,'PTIYA','SURAT'),
(106,'DHARMIK','SURAT'),
(107,'MEHUL','MORBI');

SELECT * FROM ONLINE_CUSTOMER

------------------------------------ CUSTOMER-------------------------

CREATE TABLE CUSTOMER
(
    CID INT,
    NAME VARCHAR(50),
    CITY VARCHAR(50),
    MEMBERSHIP VARCHAR(20)
);

INSERT INTO CUSTOMER VALUES
(101,'RAHUL','RAJKOT','GOLD'),
(102,'AMIT','AHMEDABAD','SILVER'),
(103,'PTIYA','SURAT','GOLD'),
(104,'HETVI','BARODA','PLATINUM'),
(105,'RIYA','RAJKOT','SILVER'),
(106,'DHARMIK','SURAT','GOLD');


SELECT * FROM CUSTOMER

------------------------------------OFFLINE_CUSTOMER------------------------


CREATE TABLE OFFLINE_CUSTOMER
(
    CID INT,
    NAME VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO OFFLINE_CUSTOMER VALUES
(102,'AMIT','AHMEDABAD'),
(104,'HETVI','BARODA'),
(105,'RIYA','RAJKOT'),
(106,'DHARMIK','SURAT');

SELECT * FROM OFFLINE_CUSTOMER


-- Lab 19 Part - A

-- Q1. Display all unique customer names from ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT Name FROM ONLINE_CUSTOMER
UNION
SELECT Name FROM OFFLINE_CUSTOMER;

-- Q2. Display all unique customer cities from ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

-- Q3. Display duplicate customer names from ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER;

-- Q4. Display unique customer IDs from ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER;

-- Q5. Display all GOLD membership customer names and online customer names using UNION.
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='GOLD'
UNION
SELECT Name FROM ONLINE_CUSTOMER;

-- Q6. Display all customer names from CUSTOMER and ONLINE_CUSTOMER using UNION.
SELECT Name FROM CUSTOMER
UNION
SELECT Name FROM ONLINE_CUSTOMER;

-- Q7. Display all cities from CUSTOMER and OFFLINE_CUSTOMER using UNION.
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

-- Q8. Display all customer IDs from CUSTOMER and OFFLINE_CUSTOMER using UNION ALL.
SELECT CID FROM CUSTOMER
UNION ALL
SELECT CID FROM OFFLINE_CUSTOMER;

-- Q9. Display all customer names from RAJKOT city using UNION.
SELECT Name FROM CUSTOMER
WHERE CITY='RAJKOT'
UNION
SELECT Name FROM ONLINE_CUSTOMER
WHERE CITY='RAJKOT'
UNION
SELECT Name FROM OFFLINE_CUSTOMER
WHERE CITY='RAJKOT';

-- Q10. Display all customer names starting with R from both tables using UNION.
SELECT Name FROM CUSTOMER
WHERE Name LIKE 'R%'
UNION
SELECT Name FROM ONLINE_CUSTOMER
WHERE Name LIKE 'R%';

-- Q11. Display customers who are both ONLINE and OFFLINE.
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER;

-- Q12. Display customer IDs existing in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT CID FROM ONLINE_CUSTOMER
INTERSECT
SELECT CID FROM OFFLINE_CUSTOMER;

-- Q13. Display customer names existing only in ONLINE_CUSTOMER.
SELECT Name FROM ONLINE_CUSTOMER
EXCEPT
SELECT Name FROM OFFLINE_CUSTOMER;

-- Q14. Display customer names existing only in OFFLINE_CUSTOMER.
SELECT Name FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name FROM ONLINE_CUSTOMER;

-- Q15. Display cities available in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT CITY FROM ONLINE_CUSTOMER
INTERSECT
SELECT CITY FROM OFFLINE_CUSTOMER;


-- Lab 19 Part - B

-- Q16. Display customer names who are GOLD members and online customers.
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='GOLD'
INTERSECT
SELECT Name FROM ONLINE_CUSTOMER;

-- Q17. Display customer names who are PLATINUM members but not online customers.
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='PLATINUM'
EXCEPT
SELECT Name FROM ONLINE_CUSTOMER;

-- Q18. Display customer IDs who are online customers but not offline customers.
SELECT CID FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID FROM OFFLINE_CUSTOMER;

-- Q19. Display customer IDs who are offline customers but not online customers.
SELECT CID FROM OFFLINE_CUSTOMER
EXCEPT
SELECT CID FROM ONLINE_CUSTOMER;

-- Q20. Display customers who are present in CUSTOMER table but not in ONLINE_CUSTOMER.
SELECT Name FROM CUSTOMER
EXCEPT
SELECT Name FROM ONLINE_CUSTOMER;

-- Q21. Display customers who are both GOLD members and available in OFFLINE_CUSTOMER.
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='GOLD'
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER;

-- Q22. Display all distinct cities from all three tables.
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

-- Q23. Display customers who are online customers and belong to SURAT city using INTERSECT.
SELECT Name FROM CUSTOMER
WHERE CITY='SURAT'
INTERSECT
SELECT Name FROM ONLINE_CUSTOMER
WHERE CITY='SURAT'

-- Q24. Display customers who are offline customers but not from RAJKOT city using MINUS/EXCEPT.
SELECT Name FROM CUSTOMER
WHERE CITY<>'RAJKOT'
EXCEPT
SELECT NAME FROM OFFLINE_CUSTOMER
WHERE CITY<>'RAJKOT'

-- Q25. Display customers who are GOLD members, online customers, and from SURAT city using INTERSECT.
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='GOLD'
INTERSECT
SELECT Name FROM ONLINE_CUSTOMER
WHERE CITY='SURAT';


-- Lab 19 Part - C

-- Q26. Display customer names who are present in at least two tables.
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM CUSTOMER
UNION
SELECT Name FROM OFFLINE_CUSTOMER
INTERSECT
SELECT Name FROM CUSTOMER;

-- Q27. Display all customer names from CUSTOMER table excluding customers available in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT Name FROM CUSTOMER
EXCEPT
(
    SELECT Name FROM ONLINE_CUSTOMER
    INTERSECT
    SELECT Name FROM OFFLINE_CUSTOMER
);

-- Q28. Display customer names who are present in both ONLINE_CUSTOMER and OFFLINE_CUSTOMER but not PLATINUM members.
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name FROM CUSTOMER
WHERE MEMBERSHIP='PLATINUM';

-- Q29. Display customer names who are either online or offline but not both.
SELECT Name FROM ONLINE_CUSTOMER
EXCEPT
SELECT Name FROM OFFLINE_CUSTOMER
UNION
SELECT Name FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name FROM ONLINE_CUSTOMER;

-- Q30. Display customer IDs present in CUSTOMER table but missing from both ONLINE_CUSTOMER and OFFLINE_CUSTOMER.
SELECT CID FROM CUSTOMER
EXCEPT
(
    SELECT CID FROM ONLINE_CUSTOMER
    UNION
    SELECT CID FROM OFFLINE_CUSTOMER
);