
--------------------CUSTOMER_ALL-----------------

CREATE TABLE CUSTOMER_ALL
(
    ORDERID INT PRIMARY KEY,
    CNAME VARCHAR(30),
    PRODUCT VARCHAR(30),
    CATEGORY VARCHAR(30),
    AMOUNT DECIMAL(10,2),
    ORDERYEAR INT,
    CITY VARCHAR(30)
);

INSERT INTO CUSTOMER_ALL VALUES
(101,'RAHUL','LAPTOP','ELECTRONICS',65000,2024,'RAJKOT'),
(102,'PRIYA','MOBILE','ELECTRONICS',25000,2023,'SURAT'),
(103,'AMIT','TABLE','FURNITURE',12000,2022,'AHMEDABAD'),
(104,'NEHA','CHAIR','FURNITURE',8000,2024,'BARODA'),
(105,'VISHAL','TV','ELECTRONICS',45000,2025,'MORBI'),
(106,'RIYA','SOFA','FURNITURE',30000,2023,'SURAT'),
(107,'MEHUL','AC','ELECTRONICS',40000,2022,'RAJKOT'),
(108,'KRUNAL','BED','FURNITURE',40000,2025,'JAMNAGAR');

SELECT * FROM CUSTOMER_ALL

--Part – A:
--1. Display top 3 highest amount orders.
WITH CTE AS
(
SELECT *,ROW_NUMBER() OVER(ORDER BY AMOUNT DESC) AS RN
FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE RN <= 3

--2. Display second highest order amount.
WITH CTE AS
(
SELECT *,
row_number() OVER(ORDER BY AMOUNT DESC) AS DR
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE DR = 2
--3. Display customers whose order amount is greater than category average amount.
WITH CAT_AVG AS
(
    SELECT CATEGORY,AVG(AMOUNT) AS AVG_AMOUNT
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT C.*
FROM CUSTOMER_ALL C
JOIN CAT_AVG A
ON C.CATEGORY = A.CATEGORY
WHERE C.AMOUNT > A.AVG_AMOUNT

--4. Display categories having average amount greater than 30000.
    WITH CAT_AVG AS
    (
        SELECT CATEGORY,AVG(AMOUNT) AS AVG_AMOUNT
        FROM CUSTOMER_ALL
        GROUP BY CATEGORY
    )
    SELECT *
    FROM CAT_AVG
    WHERE AVG_AMOUNT > 30000
--5. Display highest amount order from each category.
WITH CTE AS
(
    SELECT *,ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS RN
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE RN = 1
--6. Display lowest amount order from each category.
WITH CTE AS
(
    SELECT *,ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT ) AS RN
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE RN = 1
--7. Display categories having more than 3 orders.
WITH CAT_COUNT AS
(
    SELECT CATEGORY,COUNT(*) AS TOTAL_ORDERS
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT *
FROM CAT_COUNT
WHERE TOTAL_ORDERS > 3
--8. Display city-wise total order amount.
WITH CITY_TOTAL AS
(
    SELECT CITY,SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM CUSTOMER_ALL
    GROUP BY CITY
)
SELECT *
FROM CITY_TOTAL
--9. Display category having highest average order amount.
WITH CAT_AVG AS
(
    SELECT CATEGORY,AVG(AMOUNT) AS AVG_AMOUNT,RANK() OVER(ORDER BY AVG(AMOUNT) DESC) AS RN
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT *
FROM CAT_AVG
WHERE RN = 1
--10. Display cumulative order amount in ascending order of amount

WITH CTE AS
(
    SELECT *,SUM(AMOUNT) OVER(ORDER BY AMOUNT) AS CUMULATIVE_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE


--Part – B:
--11. Display category-wise top 2 highest amount orders.
WITH CTE AS
(
    SELECT *,ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS RN
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE RN <= 2
--12. Display customers whose amount is closest to category average amount.
WITH CAT_AVG AS
(
    SELECT CATEGORY,
           AVG(AMOUNT) AS AVG_AMOUNT
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
),
CTE AS
(
    SELECT C.*,
           ABS(C.AMOUNT - A.AVG_AMOUNT) AS DIFF,
           ROW_NUMBER() OVER
           (PARTITION BY C.CATEGORY ORDER BY ABS(C.AMOUNT - A.AVG_AMOUNT)) AS RN
    FROM CUSTOMER_ALL C JOIN CAT_AVG A
    ON C.CATEGORY = A.CATEGORY
)
SELECT *
FROM CTE
WHERE RN = 1
--13. Display previous, current and next order amount together.
WITH CTE AS
(
    SELECT ORDERID,CNAME,AMOUNT,
    LAG(AMOUNT) OVER(ORDER BY ORDERID) AS PREVIOUS_AMOUNT,
    LEAD(AMOUNT) OVER(ORDER BY ORDERID) AS NEXT_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
--14. Display customers whose amount is greater than previous customer's amount.
WITH CTE AS
(
    SELECT *,
           LAG(AMOUNT) OVER(ORDER BY ORDERID) AS PREV_AMOUNT
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE AMOUNT >PREV_AMOUNT
--15. Display customers whose rank and dense rank are different. 
WITH CTE AS
(
    SELECT *,RANK() OVER(ORDER BY AMOUNT DESC) AS RNK,DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DRNK
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE RNK <> DRNK


--Part – C:
--16. Display orders whose amount is neither highest nor lowest in their category.
WITH CTE AS
(
    SELECT *,
           MAX(AMOUNT) OVER(PARTITION BY CATEGORY) AS MAX_AMT,
           MIN(AMOUNT) OVER(PARTITION BY CATEGORY) AS MIN_AMT
    FROM CUSTOMER_ALL
)
SELECT *
FROM CTE
WHERE AMOUNT NOT IN (MAX_AMT, MIN_AMT)
--17. Display category-wise difference between highest and lowest amount.
WITH CTE AS
(
    SELECT CATEGORY,
MAX(AMOUNT) AS MAX_AMT,
MIN(AMOUNT) AS MIN_AMT
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT CATEGORY,
MAX_AMT - MIN_AMT AS DIFFERENCE
FROM CTE
--18. Display customers whose amount is greater than all FURNITURE category orders.
WITH FURN_MAX AS
(
SELECT MAX(AMOUNT) AS MAX_AMOUNT
FROM CUSTOMER_ALL
WHERE CATEGORY = 'FURNITURE'
)
SELECT *
FROM CUSTOMER_ALL
WHERE AMOUNT > (SELECT MAX_AMOUNT FROM FURN_MAX)
--19. Display categories where all orders are above 10000.
WITH CTE AS
(
    SELECT CATEGORY,
           MIN(AMOUNT) AS MIN_AMOUNT
    FROM CUSTOMER_ALL
    GROUP BY CATEGORY
)
SELECT CATEGORY
FROM CTE
WHERE MIN_AMOUNT > 10000
--20. Display customers whose amount difference from category topper is minimum. 
WITH CTE AS
(
    SELECT *,
           MAX(AMOUNT) OVER(PARTITION BY CATEGORY) AS TOP_AMOUNT
    FROM CUSTOMER_ALL
),
CTE2 AS
(
    SELECT *,TOP_AMOUNT - AMOUNT AS DIFFERENCE
    FROM CTE
)
SELECT ORDERID, CNAME, CATEGORY, AMOUNT, DIFFERENCE
FROM CTE2
WHERE DIFFERENCE =
(
    SELECT MIN(DIFFERENCE)
    FROM CTE2
);